Metrics/LineLength:
  Max: 100

Style/Documentation:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false
  
Style/ClassVars:
  Enabled: false
